Repository Harumeonglog/Harumeonglog-ServerImpl, pull requests merged in 2025-04, with the labels that each got.

#2 ✨ [Feat] post crud
  src/main/java/com/example/harumeonglog/domain/member/converter/MemberConverter.java
  src/main/java/com/example/harumeonglog/domain/post/controller/PostController.java
  src/main/java/com/example/harumeonglog/domain/post/controller/enums/PostRequestCategory.java
  src/main/java/com/example/harumeonglog/domain/post/controller/specification/PostControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/post/converter/PostConverter.java
  src/main/java/com/example/harumeonglog/domain/post/converter/PostLikeConverter.java
  src/main/java/com/example/harumeonglog/domain/post/converter/PostReportConverter.java
  src/main/java/com/example/harumeonglog/domain/post/dto/request/PostRequest.java
  src/main/java/com/example/harumeonglog/domain/post/dto/response/PostResponse.java
  src/main/java/com/example/harumeonglog/domain/post/entity/Post.java
  src/main/java/com/example/harumeonglog/domain/post/repository/PostImageRepository.java
  src/main/java/com/example/harumeonglog/domain/post/repository/PostLikeRepository.java
  src/main/java/com/example/harumeonglog/domain/post/repository/PostReportRepository.java
  src/main/java/com/example/harumeonglog/domain/post/repository/PostRepository.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostCommandService.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostQueryService.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/global/error/code/PostErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/exception/PostException.java
Labels: :sparkles: feat, :memo: docs

#7 🐛 [Fix] 소셜 로그인 allow URL 수정
  src/main/java/com/example/harumeonglog/global/security/SecurityConfig.java
Labels: :bug: bug

#11 :sparkles: [Feat] comment 삭제 구현
  src/main/java/com/example/harumeonglog/domain/comment/controller/CommentController.java
  src/main/java/com/example/harumeonglog/domain/comment/controller/specification/CommentControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/comment/entity/Comment.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentCommandService.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentQueryService.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/example/harumeonglog/global/error/code/CommentErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/exception/CommentException.java
Labels: :sparkles: feat

#9 ✨ [Feat] alarm feature 구현
  src/main/java/com/example/harumeonglog/domain/member/controller/NoticeController.java
  src/main/java/com/example/harumeonglog/domain/member/controller/specification/NoticeControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/member/converter/NoticeConverter.java
  src/main/java/com/example/harumeonglog/domain/member/dto/response/NoticeResponse.java
  src/main/java/com/example/harumeonglog/domain/member/entity/Notice.java
  src/main/java/com/example/harumeonglog/domain/member/repository/MemberRepository.java
  src/main/java/com/example/harumeonglog/domain/member/repository/NoticeRepository.java
  src/main/java/com/example/harumeonglog/domain/member/service/AppleOAuth2Service.java
  src/main/java/com/example/harumeonglog/domain/member/service/KakaoOAuth2Service.java
  src/main/java/com/example/harumeonglog/domain/member/service/NoticeCommandService.java
  src/main/java/com/example/harumeonglog/domain/member/service/NoticeCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/member/service/NoticeQueryService.java
  src/main/java/com/example/harumeonglog/domain/member/service/NoticeQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/member/service/NoticeService.java
  src/main/java/com/example/harumeonglog/domain/member/service/NoticeServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/member/service/OAuth2ServiceImpl.java
  src/main/java/com/example/harumeonglog/global/error/code/NoticeErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/exception/NoticeException.java
  src/main/java/com/example/harumeonglog/global/security/service/CustomDetailService.java
Labels: :sparkles: feat, :hammer: refactor

#13 ✨ [Feat] 로그아웃, Access Token 재발급 로직 구현
  src/main/java/com/example/harumeonglog/domain/auth/controller/AuthController.java
  src/main/java/com/example/harumeonglog/domain/auth/controller/specification/AuthControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/auth/converter/AuthConverter.java
  src/main/java/com/example/harumeonglog/domain/auth/converter/OAuth2Converter.java
  src/main/java/com/example/harumeonglog/domain/auth/dto/request/AuthRequest.java
  src/main/java/com/example/harumeonglog/domain/auth/dto/request/OAuth2Request.java
  src/main/java/com/example/harumeonglog/domain/auth/dto/response/AuthResponse.java
  src/main/java/com/example/harumeonglog/domain/auth/dto/response/OAuth2Response.java
  src/main/java/com/example/harumeonglog/domain/auth/service/AppleOAuth2Service.java
  src/main/java/com/example/harumeonglog/domain/auth/service/AuthCommandService.java
  src/main/java/com/example/harumeonglog/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/auth/service/KakaoOAuth2Service.java
  src/main/java/com/example/harumeonglog/domain/auth/service/OAuth2Service.java
  src/main/java/com/example/harumeonglog/domain/auth/service/OAuth2ServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/auth/service/RedisCommandService.java
  src/main/java/com/example/harumeonglog/domain/auth/service/RedisCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/auth/service/RedisQueryService.java
  src/main/java/com/example/harumeonglog/domain/auth/service/RedisQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/auth/service/TokenCommandService.java
  src/main/java/com/example/harumeonglog/domain/auth/service/TokenCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/auth/service/TokenQueryService.java
  src/main/java/com/example/harumeonglog/domain/auth/service/TokenServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/member/controller/MemberController.java
  src/main/java/com/example/harumeonglog/domain/member/controller/specification/MemberControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/member/converter/MemberConverter.java
  src/main/java/com/example/harumeonglog/domain/member/dto/request/MemberRequest.java
  src/main/java/com/example/harumeonglog/domain/member/dto/response/MemberResponse.java
  src/main/java/com/example/harumeonglog/domain/member/service/MemberService.java
  src/main/java/com/example/harumeonglog/domain/member/service/MemberServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/post/converter/PostConverter.java
  src/main/java/com/example/harumeonglog/domain/post/dto/response/PostResponse.java
  src/main/java/com/example/harumeonglog/global/data/RedisConfigData.java
  src/main/java/com/example/harumeonglog/global/error/code/AuthErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/code/TokenErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/exception/TokenException.java
  src/main/java/com/example/harumeonglog/global/security/SecurityConfig.java
  src/main/java/com/example/harumeonglog/global/security/filter/AbstractTokenLogoutFilter.java
  src/main/java/com/example/harumeonglog/global/security/filter/JwtTokenFilter.java
  src/main/java/com/example/harumeonglog/global/security/filter/JwtTokenLogoutFilter.java
  src/main/java/com/example/harumeonglog/global/security/service/CustomDetailService.java
  src/main/java/com/example/harumeonglog/global/util/JwtUtil.java
  src/main/java/com/example/harumeonglog/global/util/RedisUtil.java
Labels: :sparkles: feat

#16 🐛 [Fix] post softdelete
  src/main/java/com/example/harumeonglog/domain/post/controller/PostController.java
  src/main/java/com/example/harumeonglog/domain/post/controller/specification/PostControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/post/entity/Post.java
  src/main/java/com/example/harumeonglog/domain/post/repository/PostRepository.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostQueryServiceImpl.java
Labels: :bug: bug, :sparkles: feat, :memo: docs

#19 🐛 [Fix] post valid
  src/main/java/com/example/harumeonglog/domain/post/controller/PostController.java
  src/main/java/com/example/harumeonglog/domain/post/controller/specification/PostControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostCommandService.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/global/error/code/PostErrorCode.java
Labels: :bug: bug, :hammer: refactor

#21 :zap: [Perf] post 페이지네이션 시 N + 1 문제 해결
  src/main/java/com/example/harumeonglog/domain/post/controller/PostController.java
  src/main/java/com/example/harumeonglog/domain/post/repository/PostRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: ⚡perf

#22 ✨ [Feat] Member API 구현
  src/main/java/com/example/harumeonglog/domain/auth/service/AppleOAuth2Service.java
  src/main/java/com/example/harumeonglog/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/auth/service/KakaoOAuth2Service.java
  src/main/java/com/example/harumeonglog/domain/auth/service/OAuth2ServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/auth/service/RedisCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/auth/service/RedisQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/auth/service/TokenCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/auth/service/TokenQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/member/controller/MemberController.java
  src/main/java/com/example/harumeonglog/domain/member/controller/specification/MemberControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/member/converter/MemberConverter.java
  src/main/java/com/example/harumeonglog/domain/member/converter/SettingConverter.java
  src/main/java/com/example/harumeonglog/domain/member/dto/request/MemberRequest.java
  src/main/java/com/example/harumeonglog/domain/member/dto/response/MemberResponse.java
  src/main/java/com/example/harumeonglog/domain/member/dto/response/SettingResponse.java
  src/main/java/com/example/harumeonglog/domain/member/entity/Member.java
  src/main/java/com/example/harumeonglog/domain/member/entity/Setting.java
  src/main/java/com/example/harumeonglog/domain/member/repository/SettingRepository.java
  src/main/java/com/example/harumeonglog/domain/member/service/MemberCommandService.java
  src/main/java/com/example/harumeonglog/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/member/service/MemberService.java
  src/main/java/com/example/harumeonglog/domain/member/service/MemberServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/member/service/SettingCommandService.java
  src/main/java/com/example/harumeonglog/domain/member/service/SettingCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/member/service/SettingQueryService.java
  src/main/java/com/example/harumeonglog/domain/member/service/SettingQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/member/service/SettingService.java
  src/main/java/com/example/harumeonglog/domain/member/service/SettingServiceImpl.java
  src/main/java/com/example/harumeonglog/global/error/code/SettingErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/exception/SettingException.java
Labels: :sparkles: feat

#24 ✨ [Feat] comment read
  src/main/java/com/example/harumeonglog/domain/comment/controller/CommentController.java
  src/main/java/com/example/harumeonglog/domain/comment/controller/specification/CommentControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/comment/converter/CommentConverter.java
  src/main/java/com/example/harumeonglog/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/example/harumeonglog/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentQueryService.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentQueryServiceImpl.java
Labels: :sparkles: feat, :memo: docs

#26 🐛 [Fix] post response dto 수정
  src/main/java/com/example/harumeonglog/domain/post/controller/PostController.java
  src/main/java/com/example/harumeonglog/domain/post/controller/specification/PostControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/post/converter/PostConverter.java
  src/main/java/com/example/harumeonglog/domain/post/dto/response/PostResponse.java
  src/main/java/com/example/harumeonglog/domain/post/entity/Post.java
  src/main/java/com/example/harumeonglog/domain/post/entity/PostImage.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostCommandService.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostCommandServiceImpl.java
Labels: :bug: fix, :hammer: refactor

#36 :memo: [Docs] 알림 스웨거 수정
  src/main/java/com/example/harumeonglog/domain/member/controller/specification/NoticeControllerSpecification.java
Labels: :memo: docs

#34 🔨 [Refactor] post associate
  src/main/java/com/example/harumeonglog/domain/post/converter/PostImageConverter.java
  src/main/java/com/example/harumeonglog/domain/post/entity/Post.java
  src/main/java/com/example/harumeonglog/domain/post/entity/PostImage.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostCommandServiceImpl.java
Labels: :hammer: refactor

#32 ✨ [Feat] comment feature
  src/main/java/com/example/harumeonglog/domain/comment/controller/CommentController.java
  src/main/java/com/example/harumeonglog/domain/comment/controller/specification/CommentControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/comment/converter/CommentBlockConverter.java
  src/main/java/com/example/harumeonglog/domain/comment/converter/CommentConverter.java
  src/main/java/com/example/harumeonglog/domain/comment/converter/CommentLikeConverter.java
  src/main/java/com/example/harumeonglog/domain/comment/converter/CommentReportConverter.java
  src/main/java/com/example/harumeonglog/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/example/harumeonglog/domain/comment/entity/Comment.java
  src/main/java/com/example/harumeonglog/domain/comment/entity/CommentBlock.java
  src/main/java/com/example/harumeonglog/domain/comment/entity/CommentLike.java
  src/main/java/com/example/harumeonglog/domain/comment/entity/CommentReport.java
  src/main/java/com/example/harumeonglog/domain/comment/repository/CommentBlockRepository.java
  src/main/java/com/example/harumeonglog/domain/comment/repository/CommentLikeRepository.java
  src/main/java/com/example/harumeonglog/domain/comment/repository/CommentReportRepository.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentCommandService.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/post/entity/Post.java
  src/main/java/com/example/harumeonglog/global/error/ExceptionAdvice.java
  src/main/java/com/example/harumeonglog/global/error/code/CommentErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/code/GeneralErrorCode.java
Labels: :bug: fix, :sparkles: feat, :memo: docs, :hammer: refactor

#31 🐛 [Fix] JWT 내부 불필요 데이터 삭제
  src/main/java/com/example/harumeonglog/global/util/JwtUtil.java
Labels: :bug: fix

#38 🐛 [Fix] Swagger 인증이 메인 인증 로직에 영향을 주지 않도록 수정
  src/main/java/com/example/harumeonglog/global/security/SecurityConfig.java
Labels: :bug: fix

#14 ✨ [Feat] pet, petImage API 구현
  build.gradle
  src/main/java/com/example/harumeonglog/domain/member/entity/Member.java
  src/main/java/com/example/harumeonglog/domain/member/repository/MemberRepository.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/PetController.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/PetImageController.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/specification/PetControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/specification/PetImageControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/pet/converter/MemberPetConverter.java
  src/main/java/com/example/harumeonglog/domain/pet/converter/PetConverter.java
  src/main/java/com/example/harumeonglog/domain/pet/converter/PetImageConverter.java
  src/main/java/com/example/harumeonglog/domain/pet/dto/request/PetImageRequest.java
  src/main/java/com/example/harumeonglog/domain/pet/dto/request/PetRequest.java
  src/main/java/com/example/harumeonglog/domain/pet/dto/response/PetImageResponse.java
  src/main/java/com/example/harumeonglog/domain/pet/dto/response/PetResponse.java
  src/main/java/com/example/harumeonglog/domain/pet/entity/MemberPet.java
  src/main/java/com/example/harumeonglog/domain/pet/entity/Pet.java
  src/main/java/com/example/harumeonglog/domain/pet/entity/enums/Gender.java
  src/main/java/com/example/harumeonglog/domain/pet/repository/MemberPetRepository.java
  src/main/java/com/example/harumeonglog/domain/pet/repository/PetImageRepository.java
  src/main/java/com/example/harumeonglog/domain/pet/repository/PetRepository.java
  src/main/java/com/example/harumeonglog/domain/pet/service/PetImageService.java
  src/main/java/com/example/harumeonglog/domain/pet/service/PetImageServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/pet/service/PetService.java
  src/main/java/com/example/harumeonglog/domain/pet/service/PetServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/pet/service/command/PetCommandService.java
  src/main/java/com/example/harumeonglog/domain/pet/service/command/PetCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/pet/service/command/PetImageCommandService.java
  src/main/java/com/example/harumeonglog/domain/pet/service/command/PetImageCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/pet/service/query/PetImageQueryService.java
  src/main/java/com/example/harumeonglog/domain/pet/service/query/PetImageQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/pet/service/query/PetQueryService.java
  src/main/java/com/example/harumeonglog/domain/pet/service/query/PetQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/post/repository/PostImageRepository.java
  src/main/java/com/example/harumeonglog/global/config/S3Config.java
  src/main/java/com/example/harumeonglog/global/config/WebConfig.java
  src/main/java/com/example/harumeonglog/global/data/S3ConfigData.java
  src/main/java/com/example/harumeonglog/global/error/code/PetErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/code/S3ErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/exception/PetException.java
  src/main/java/com/example/harumeonglog/global/error/exception/S3Exception.java
  src/main/java/com/example/harumeonglog/global/s3/controller/S3Controller.java
  src/main/java/com/example/harumeonglog/global/s3/controller/specification/S3ControllerSpecification.java
  src/main/java/com/example/harumeonglog/global/s3/converter/S3Converter.java
  src/main/java/com/example/harumeonglog/global/s3/dto/request/S3RequestDTO.java
  src/main/java/com/example/harumeonglog/global/s3/dto/response/S3ResponseDTO.java
  src/main/java/com/example/harumeonglog/global/s3/enums/S3Domain.java
  src/main/java/com/example/harumeonglog/global/s3/scheduler/S3CleanupScheduler.java
  src/main/java/com/example/harumeonglog/global/s3/service/S3Service.java
  src/main/java/com/example/harumeonglog/global/s3/service/S3ServiceImpl.java
  src/main/java/com/example/harumeonglog/global/util/S3Util.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: :sparkles: feat, :hammer: refactor

#42 🐛 [Fix] 대댓글 로직 추가
  src/main/java/com/example/harumeonglog/domain/comment/controller/CommentController.java
  src/main/java/com/example/harumeonglog/domain/comment/controller/specification/CommentControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/comment/converter/CommentConverter.java
  src/main/java/com/example/harumeonglog/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/example/harumeonglog/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/example/harumeonglog/domain/comment/entity/Comment.java
  src/main/java/com/example/harumeonglog/domain/comment/repository/CommentBlockRepository.java
  src/main/java/com/example/harumeonglog/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentQueryService.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/post/entity/Post.java
  src/main/java/com/example/harumeonglog/global/error/code/CommentErrorCode.java
Labels: :bug: fix, :sparkles: feat

#47 :bug: [Fix]: PetImage 컨트롤러 어노테이션 수정
  src/main/java/com/example/harumeonglog/domain/pet/controller/PetImageController.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/specification/PetImageControllerSpecification.java
Labels: :bug: fix

#44 ✨ [Feat] FCM 구현
  build.gradle
  src/main/java/com/example/harumeonglog/domain/member/controller/MemberController.java
  src/main/java/com/example/harumeonglog/domain/member/dto/request/MemberRequest.java
  src/main/java/com/example/harumeonglog/domain/member/entity/Member.java
  src/main/java/com/example/harumeonglog/domain/member/repository/MemberRepository.java
  src/main/java/com/example/harumeonglog/domain/member/repository/NoticeRepository.java
  src/main/java/com/example/harumeonglog/domain/member/service/MemberCommandService.java
  src/main/java/com/example/harumeonglog/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/global/error/code/AuthErrorCode.java
  src/main/java/com/example/harumeonglog/global/firebase/FirebaseConfig.java
  src/main/java/com/example/harumeonglog/global/firebase/service/FcmService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: :sparkles: feat

#45 ✨[Feat] Event API 구현
  src/main/java/com/example/harumeonglog/domain/event/controller/EventController.java
  src/main/java/com/example/harumeonglog/domain/event/controller/sepcification/EventControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/event/converter/EventConverter.java
  src/main/java/com/example/harumeonglog/domain/event/dto/request/EventRequest.java
  src/main/java/com/example/harumeonglog/domain/event/dto/response/EventResponse.java
  src/main/java/com/example/harumeonglog/domain/event/entity/BathEvent.java
  src/main/java/com/example/harumeonglog/domain/event/entity/Event.java
  src/main/java/com/example/harumeonglog/domain/event/entity/GeneralEvent.java
  src/main/java/com/example/harumeonglog/domain/event/entity/HospitalEvent.java
  src/main/java/com/example/harumeonglog/domain/event/entity/MedicineEvent.java
  src/main/java/com/example/harumeonglog/domain/event/entity/WalkEvent.java
  src/main/java/com/example/harumeonglog/domain/event/entity/enums/RepeatDay.java
  src/main/java/com/example/harumeonglog/domain/event/repository/EventRepository.java
  src/main/java/com/example/harumeonglog/domain/event/service/EventService.java
  src/main/java/com/example/harumeonglog/domain/event/service/EventServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/event/service/command/EventCommandService.java
  src/main/java/com/example/harumeonglog/domain/event/service/command/EventCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/event/service/query/EventQueryService.java
  src/main/java/com/example/harumeonglog/domain/event/service/query/EventQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/global/error/code/EventErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/exception/EventException.java
Labels: :sparkles: feat

#52 ✨ [Feat] 산책 API 구현
  src/main/java/com/example/harumeonglog/domain/pet/repository/MemberPetRepository.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/WalkController.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/specification/WalkControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/walk/converter/MemberWalkConverter.java
  src/main/java/com/example/harumeonglog/domain/walk/converter/TrackConverter.java
  src/main/java/com/example/harumeonglog/domain/walk/converter/WalkConverter.java
  src/main/java/com/example/harumeonglog/domain/walk/converter/WalkLikeConverter.java
  src/main/java/com/example/harumeonglog/domain/walk/converter/WalkPetConverter.java
  src/main/java/com/example/harumeonglog/domain/walk/converter/WalkPositionConverter.java
  src/main/java/com/example/harumeonglog/domain/walk/dto/request/MemberWalkRequest.java
  src/main/java/com/example/harumeonglog/domain/walk/dto/request/WalkRequest.java
  src/main/java/com/example/harumeonglog/domain/walk/dto/response/MemberWalkResponse.java
  src/main/java/com/example/harumeonglog/domain/walk/dto/response/WalkPetResponse.java
  src/main/java/com/example/harumeonglog/domain/walk/dto/response/WalkResponse.java
  src/main/java/com/example/harumeonglog/domain/walk/entity/Track.java
  src/main/java/com/example/harumeonglog/domain/walk/entity/Walk.java
  src/main/java/com/example/harumeonglog/domain/walk/entity/enums/WalkStatus.java
  src/main/java/com/example/harumeonglog/domain/walk/repository/MemberWalkRepository.java
  src/main/java/com/example/harumeonglog/domain/walk/repository/TrackRepository.java
  src/main/java/com/example/harumeonglog/domain/walk/repository/WalkLikeRepository.java
  src/main/java/com/example/harumeonglog/domain/walk/repository/WalkPetRepository.java
  src/main/java/com/example/harumeonglog/domain/walk/repository/WalkPositionRepository.java
  src/main/java/com/example/harumeonglog/domain/walk/repository/WalkRepository.java
  src/main/java/com/example/harumeonglog/domain/walk/service/MemberWalkCommandService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/MemberWalkCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/MemberWalkService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/MemberWalkServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/TrackCommandService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/TrackCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/TrackQueryService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/TrackQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkCommandService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkLikeCommandService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkLikeCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkPetCommandService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkPetCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkPositionCommandService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkPositionCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkPositionQueryService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkPositionQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkQueryService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkServiceImpl.java
  src/main/java/com/example/harumeonglog/global/error/code/TrackErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/code/WalkErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/exception/TrackException.java
  src/main/java/com/example/harumeonglog/global/error/exception/WalkException.java
  src/main/java/com/example/harumeonglog/global/util/DistanceUtil.java
Labels: :sparkles: feat

#50 ⚡ [Perf] FCM outbox 패턴 적용
  src/main/java/com/example/harumeonglog/HarumeonglogApplication.java
  src/main/java/com/example/harumeonglog/global/common/util/JsonUtils.java
  src/main/java/com/example/harumeonglog/global/error/code/JsonDeserializationErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/exception/JsonDeserializationException.java
  src/main/java/com/example/harumeonglog/global/firebase/service/FcmService.java
  src/main/java/com/example/harumeonglog/global/outbox/converter/OutBoxConverter.java
  src/main/java/com/example/harumeonglog/global/outbox/dto/FcmPayload.java
  src/main/java/com/example/harumeonglog/global/outbox/entity/OutBox.java
  src/main/java/com/example/harumeonglog/global/outbox/entity/enums/EventType.java
  src/main/java/com/example/harumeonglog/global/outbox/repository/OutBoxRepository.java
  src/main/java/com/example/harumeonglog/global/outbox/scheduler/OutBoxScheduler.java
  src/main/java/com/example/harumeonglog/global/outbox/service/OutBoxService.java
  src/main/java/com/example/harumeonglog/global/outbox/service/OutBoxServiceImpl.java
Labels: ⚡perf

#54 ✨ [Feat] Cors 설정
  src/main/java/com/example/harumeonglog/global/data/CorsConfigData.java
  src/main/java/com/example/harumeonglog/global/security/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: :sparkles: feat

#57 🐛 [Fix] Swagger용 로그아웃 Controller 응답 수정
  src/main/java/com/example/harumeonglog/domain/auth/controller/AuthController.java
  src/main/java/com/example/harumeonglog/domain/auth/controller/specification/AuthControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/auth/service/AuthCommandService.java
  src/main/java/com/example/harumeonglog/domain/auth/service/AuthCommandServiceImpl.java
Labels: :bug: fix

#58 ✨ [Feat] post title
  src/main/java/com/example/harumeonglog/domain/post/controller/PostController.java
  src/main/java/com/example/harumeonglog/domain/post/converter/PostConverter.java
  src/main/java/com/example/harumeonglog/domain/post/dto/request/PostRequest.java
  src/main/java/com/example/harumeonglog/domain/post/dto/response/PostResponse.java
  src/main/java/com/example/harumeonglog/domain/post/entity/Post.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostCommandServiceImpl.java
Labels: :sparkles: feat

#60 [Docs] 헬스체킹, fcm 저장 memo
  src/main/java/com/example/harumeonglog/domain/member/controller/specification/MemberControllerSpecification.java
  src/main/java/com/example/harumeonglog/global/common/HealthCheckController.java
Labels: :memo: docs
