Repository Harumeonglog/Harumeonglog-ServerImpl, pull requests merged in 2025-05, with the labels that each got.

#66 ✨ [Feat] cursor valid
  src/main/java/com/example/harumeonglog/domain/comment/controller/CommentController.java
  src/main/java/com/example/harumeonglog/domain/comment/controller/specification/CommentControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/member/controller/NoticeController.java
  src/main/java/com/example/harumeonglog/domain/member/controller/specification/NoticeControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/post/controller/PostController.java
  src/main/java/com/example/harumeonglog/domain/post/controller/specification/PostControllerSpecification.java
  src/main/java/com/example/harumeonglog/global/error/code/GeneralErrorCode.java
  src/main/java/com/example/harumeonglog/global/validation/annotation/CheckCursorValidation.java
  src/main/java/com/example/harumeonglog/global/validation/annotation/CheckSizeValidation.java
  src/main/java/com/example/harumeonglog/global/validation/validator/CheckCursorValidator.java
  src/main/java/com/example/harumeonglog/global/validation/validator/CheckSizeValidator.java
Labels: :sparkles: feat

#67 🐛 [Fix] 산책 거리, 시간 적용 로직 삭제 및 DTO로 받도록 변경
  src/main/java/com/example/harumeonglog/domain/walk/controller/WalkController.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/specification/WalkControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/walk/dto/request/WalkRequest.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkCommandService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkCommandServiceImpl.java
Labels: :bug: fix

#71 ✨ [Feat] 산책 커서 페이지네이션에 validation 적용
  src/main/java/com/example/harumeonglog/domain/walk/controller/WalkController.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/specification/WalkControllerSpecification.java
Labels: :sparkles: feat

#73 🐛 [Fix] 로그인 시 정보 동기화 및 사용자 불필요 필드 삭제
  src/main/java/com/example/harumeonglog/domain/auth/converter/OAuth2Converter.java
  src/main/java/com/example/harumeonglog/domain/auth/dto/request/OAuth2Request.java
  src/main/java/com/example/harumeonglog/domain/auth/service/KakaoOAuth2Service.java
  src/main/java/com/example/harumeonglog/domain/auth/service/OAuth2ServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/member/converter/MemberConverter.java
  src/main/java/com/example/harumeonglog/domain/member/dto/response/MemberResponse.java
  src/main/java/com/example/harumeonglog/domain/member/entity/Member.java
Labels: :bug: fix

#75 🐛 [Fix] CORS 수정
  src/main/resources/application-dev.yml
Labels: :bug: fix

#69 ✨ [Feat]: Pet, PetImage, Event cursor valid
  src/main/java/com/example/harumeonglog/domain/event/controller/EventController.java
  src/main/java/com/example/harumeonglog/domain/event/controller/sepcification/EventControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/PetController.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/PetImageController.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/specification/PetControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/specification/PetImageControllerSpecification.java
Labels: :sparkles: feat

#80 🚀 [Chore] outbox eventType 변경
  src/main/java/com/example/harumeonglog/global/outbox/entity/OutBox.java
Labels: :rocket: chore

#85 🔨 [Refactor] Pet, Event, S3 controller formatting
  src/main/java/com/example/harumeonglog/domain/event/controller/EventController.java
  src/main/java/com/example/harumeonglog/domain/event/controller/sepcification/EventControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/PetController.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/PetImageController.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/specification/PetControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/specification/PetImageControllerSpecification.java
  src/main/java/com/example/harumeonglog/global/s3/controller/S3Controller.java
  src/main/java/com/example/harumeonglog/global/s3/controller/specification/S3ControllerSpecification.java
Labels: :hammer: refactor

#84 🔨 [Refactor] Controller & Specification 코드 통합
  src/main/java/com/example/harumeonglog/domain/auth/controller/AuthController.java
  src/main/java/com/example/harumeonglog/domain/auth/controller/specification/AuthControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/member/controller/MemberController.java
  src/main/java/com/example/harumeonglog/domain/member/controller/specification/MemberControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/WalkController.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/specification/WalkControllerSpecification.java
Labels: :hammer: refactor

#87 🚀 [Chore] controller 통합
  src/main/java/com/example/harumeonglog/domain/comment/controller/CommentController.java
  src/main/java/com/example/harumeonglog/domain/comment/controller/specification/CommentControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/member/controller/NoticeController.java
  src/main/java/com/example/harumeonglog/domain/member/controller/specification/NoticeControllerSpecification.java
  src/main/java/com/example/harumeonglog/domain/post/controller/PostController.java
  src/main/java/com/example/harumeonglog/domain/post/controller/specification/PostControllerSpecification.java
Labels: :rocket: chore

#91 :sparkles: [Feat] post content 추가 및 진행 시간 추가
  src/main/java/com/example/harumeonglog/domain/post/converter/PostConverter.java
  src/main/java/com/example/harumeonglog/domain/post/dto/response/PostResponse.java
Labels: :sparkles: feat

#93 :bug: [Fix] 시간 유형 변경
  src/main/java/com/example/harumeonglog/domain/post/converter/PostConverter.java
  src/main/java/com/example/harumeonglog/domain/post/dto/response/PostResponse.java
Labels: :bug: fix

#95 ✨ [Feat] db error 분기 추가
  src/main/java/com/example/harumeonglog/domain/comment/entity/CommentBlock.java
  src/main/java/com/example/harumeonglog/domain/comment/entity/CommentLike.java
  src/main/java/com/example/harumeonglog/domain/comment/entity/CommentReport.java
  src/main/java/com/example/harumeonglog/domain/post/entity/PostBlock.java
  src/main/java/com/example/harumeonglog/domain/post/entity/PostLike.java
  src/main/java/com/example/harumeonglog/domain/post/entity/PostReport.java
  src/main/java/com/example/harumeonglog/global/error/ExceptionAdvice.java
  src/main/java/com/example/harumeonglog/global/error/code/GeneralErrorCode.java
Labels: :sparkles: feat

#81 ✨ [Feat] S3 Outbox Pattern 적용
  src/main/java/com/example/harumeonglog/domain/pet/converter/PetImageConverter.java
  src/main/java/com/example/harumeonglog/domain/pet/service/command/PetCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/pet/service/command/PetImageCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/global/error/code/OutboxErrorCode.java
  src/main/java/com/example/harumeonglog/global/error/exception/OutboxException.java
  src/main/java/com/example/harumeonglog/global/outbox/converter/OutBoxConverter.java
  src/main/java/com/example/harumeonglog/global/outbox/entity/enums/EventType.java
  src/main/java/com/example/harumeonglog/global/outbox/repository/OutBoxRepository.java
  src/main/java/com/example/harumeonglog/global/outbox/scheduler/OutBoxScheduler.java
  src/main/java/com/example/harumeonglog/global/outbox/service/OutBoxServiceImpl.java
  src/main/java/com/example/harumeonglog/global/s3/service/S3ServiceImpl.java
  src/main/java/com/example/harumeonglog/global/util/OutboxUtil.java
  src/main/java/com/example/harumeonglog/global/util/S3Util.java
Labels: :bug: fix, :sparkles: feat

#97 🐛 [Fix] 일정 쿼리문, 현재 펫 변경 로직 수정
  src/main/java/com/example/harumeonglog/domain/event/controller/EventController.java
  src/main/java/com/example/harumeonglog/domain/event/repository/EventRepository.java
  src/main/java/com/example/harumeonglog/domain/event/service/query/EventQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/pet/service/command/PetCommandServiceImpl.java
Labels: :bug: fix

#100 🐛 [Fix] Member Image 로직 수정
  src/main/java/com/example/harumeonglog/domain/comment/converter/CommentConverter.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/member/controller/MemberController.java
  src/main/java/com/example/harumeonglog/domain/member/converter/MemberConverter.java
  src/main/java/com/example/harumeonglog/domain/member/dto/request/MemberRequest.java
  src/main/java/com/example/harumeonglog/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostQueryServiceImpl.java
Labels: :bug: fix

#105 ✨ [Feat] post logic 추가
  src/main/java/com/example/harumeonglog/domain/comment/converter/CommentConverter.java
  src/main/java/com/example/harumeonglog/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/example/harumeonglog/domain/comment/entity/Comment.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/post/controller/PostController.java
  src/main/java/com/example/harumeonglog/domain/post/converter/PostConverter.java
  src/main/java/com/example/harumeonglog/domain/post/dto/response/PostResponse.java
  src/main/java/com/example/harumeonglog/domain/post/entity/Post.java
  src/main/java/com/example/harumeonglog/domain/post/repository/PostLikeRepository.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostQueryService.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostQueryServiceImpl.java
Labels: :sparkles: feat
