Repository Harumeonglog/Harumeonglog-ServerImpl, pull requests merged in 2025-07, with the labels that each got.

#138 ✨ [Feat] 일정 알림, 펫 초대 API
  src/main/java/com/example/harumeonglog/domain/event/entity/Event.java
  src/main/java/com/example/harumeonglog/domain/event/repository/EventRepository.java
  src/main/java/com/example/harumeonglog/domain/event/scheduler/EventScheduler.java
  src/main/java/com/example/harumeonglog/domain/member/converter/InvitationConverter.java
  src/main/java/com/example/harumeonglog/domain/member/dto/response/InvitationResponse.java
  src/main/java/com/example/harumeonglog/domain/member/entity/enums/NoticeType.java
  src/main/java/com/example/harumeonglog/domain/member/repository/InvitationRepository.java
  src/main/java/com/example/harumeonglog/domain/member/repository/SettingRepository.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/PetController.java
  src/main/java/com/example/harumeonglog/domain/pet/converter/PetConverter.java
  src/main/java/com/example/harumeonglog/domain/pet/dto/request/PetRequest.java
  src/main/java/com/example/harumeonglog/domain/pet/entity/enums/MemberPetRole.java
  src/main/java/com/example/harumeonglog/domain/pet/service/command/PetCommandService.java
  src/main/java/com/example/harumeonglog/domain/pet/service/command/PetCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/pet/service/query/PetQueryService.java
  src/main/java/com/example/harumeonglog/domain/pet/service/query/PetQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/global/error/code/PetErrorCode.java
  src/main/java/com/example/harumeonglog/global/util/FcmUtil.java
Labels: :sparkles: feat

#144 :sparkles: [Feat] 현재 펫 변경 조회 시 role 추가
  src/main/java/com/example/harumeonglog/domain/pet/converter/MemberPetConverter.java
  src/main/java/com/example/harumeonglog/domain/pet/dto/response/PetResponse.java
  src/main/java/com/example/harumeonglog/domain/pet/service/query/PetQueryServiceImpl.java
Labels: :sparkles: feat

#150 ✨ [Feat] 애플 로그인 구현
  src/main/java/com/example/harumeonglog/domain/auth/service/AppleOAuth2Service.java
  src/main/java/com/example/harumeonglog/domain/member/converter/MemberConverter.java
  src/main/java/com/example/harumeonglog/global/data/AppleOAuthConfigData.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: :sparkles: feat

#151 :hammer: [Refactor] 알림 간소화
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/event/scheduler/EventScheduler.java
  src/main/java/com/example/harumeonglog/domain/member/converter/NoticeConverter.java
  src/main/java/com/example/harumeonglog/domain/member/entity/Notice.java
  src/main/java/com/example/harumeonglog/domain/member/service/NoticeCommandService.java
  src/main/java/com/example/harumeonglog/domain/member/service/NoticeCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/pet/service/command/PetCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/global/config/AsyncConfig.java
  src/main/java/com/example/harumeonglog/global/firebase/service/FcmService.java
  src/main/java/com/example/harumeonglog/global/outbox/scheduler/OutBoxScheduler.java
  src/main/java/com/example/harumeonglog/global/outbox/service/OutBoxService.java
  src/main/java/com/example/harumeonglog/global/outbox/service/OutBoxServiceImpl.java
Labels: :hammer: refactor

#153 ✨ [Feat] post me
  src/main/java/com/example/harumeonglog/domain/post/converter/PostConverter.java
  src/main/java/com/example/harumeonglog/domain/post/dto/response/PostResponse.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostQueryServiceImpl.java
Labels: :sparkles: feat

#156 🐛 [Fix] Pet 나가기, Pet 정보 수정 로직 수정
  src/main/java/com/example/harumeonglog/domain/pet/controller/PetController.java
  src/main/java/com/example/harumeonglog/domain/pet/repository/MemberPetRepository.java
  src/main/java/com/example/harumeonglog/domain/pet/repository/PetRepository.java
  src/main/java/com/example/harumeonglog/domain/pet/service/command/PetCommandService.java
  src/main/java/com/example/harumeonglog/domain/pet/service/command/PetCommandServiceImpl.java
Labels: :bug: fix, :hammer: refactor
