Repository Harumeonglog/Harumeonglog-ServerImpl, pull requests merged in 2025-06, with the labels that each got.

#109 :hammer: [Refactor] S3 outbox 조회 시 재시도 회수 조건 추가
  src/main/java/com/example/harumeonglog/global/outbox/repository/OutBoxRepository.java
  src/main/java/com/example/harumeonglog/global/outbox/scheduler/OutBoxScheduler.java
Labels: :hammer: refactor

#110 ✨ [Feature] 홈화면 페이지 조회 API 및 Redis 캐시 적용
  src/main/java/com/example/harumeonglog/domain/post/controller/PostController.java
  src/main/java/com/example/harumeonglog/domain/post/converter/PostConverter.java
  src/main/java/com/example/harumeonglog/domain/post/dto/response/PostResponse.java
  src/main/java/com/example/harumeonglog/domain/post/repository/PostRepository.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostQueryService.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/global/config/RedisCacheConfig.java
Labels: :sparkles: feat, ⚡perf

#116 ✨ [Feat] post category error 처리 개선
  src/main/java/com/example/harumeonglog/domain/post/dto/request/PostRequest.java
  src/main/java/com/example/harumeonglog/global/error/ExceptionAdvice.java
  src/main/java/com/example/harumeonglog/global/error/code/GeneralErrorCode.java
Labels: :sparkles: feat

#120 :sparkles: [Feat] 알림 생성 시간 추가
  src/main/java/com/example/harumeonglog/domain/member/converter/NoticeConverter.java
  src/main/java/com/example/harumeonglog/domain/member/dto/response/NoticeResponse.java
  src/main/java/com/example/harumeonglog/domain/member/entity/Notice.java
Labels: :sparkles: feat

#125 🐛 [Fix] 산책 이미지 반환 값 URL로 변경
  src/main/java/com/example/harumeonglog/domain/walk/converter/WalkConverter.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkQueryServiceImpl.java
Labels: :bug: fix

#128 🔨 [Refactor] postquery 리펙토링
  src/main/java/com/example/harumeonglog/domain/post/controller/enums/PostRequestCategory.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostQueryServiceImpl.java
Labels: :hammer: refactor

#130 :test_tube: [Test] 수정, 삭제 시 자신의 것이 아니면 에러가 나는 지에 대한 테스트
  src/test/java/com/example/harumeonglog/domain/post/service/PostCommandServiceImplTest.java
Labels: :test_tube: test

#135 🐛 [Fix] 산책 거리 응답 형식 변경
  src/main/java/com/example/harumeonglog/domain/walk/converter/WalkConverter.java
  src/main/java/com/example/harumeonglog/domain/walk/dto/response/WalkResponse.java
  src/main/java/com/example/harumeonglog/domain/walk/entity/Walk.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkCommandServiceImpl.java
Labels: :bug: fix

#137 🐛 [Fix] 산책 성공 후 일정 자동 생성
  src/main/java/com/example/harumeonglog/domain/event/dto/request/EventRequest.java
  src/main/java/com/example/harumeonglog/domain/event/service/command/EventCommandService.java
  src/main/java/com/example/harumeonglog/domain/event/service/command/EventCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/repository/MemberWalkRepository.java
  src/main/java/com/example/harumeonglog/domain/walk/repository/WalkPetRepository.java
  src/main/java/com/example/harumeonglog/domain/walk/service/MemberWalkQueryService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/MemberWalkQueryServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkPetQueryService.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkPetQueryServiceImpl.java
Labels: :bug: fix

#133 🐛 [Fix] 산책 쿼리 수정
  src/main/java/com/example/harumeonglog/domain/walk/repository/MemberWalkRepository.java
  src/main/java/com/example/harumeonglog/domain/walk/repository/WalkLikeRepository.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkQueryServiceImpl.java
Labels: :bug: fix, ⚡perf
